# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
- role: control-plane
- role: worker
- role: worker
# kubeadmConfigPatches:
# - |
#   apiVersion: kubeadm.k8s.io/v1alpha4
#   kind: ClusterConfiguration
#   metadata:
#     name: config
#   featureGates:
#     EphemeralContainers: true